"""Build the target word list from the CEFR-labelled source datasets.

    python -m pipeline.build_wordlist

Reads `wordlists/sources/` and writes `wordlists/targets.tsv`.

Why this exists rather than a hand-kept list: difficulty has to be a property
of the input, not something the generator guesses. Every target word carries a
CEFR level from a cited dataset, so calling a question B2 is a claim that
traces back to published data instead of a label we invented.

Licences (verified 5 September 2026, see CLAUDE.md section 5):
  - CEFR-J Wordlist v1.5 — free for commercial use with citation.
    © Tono Laboratory, Tokyo University of Foreign Studies.
  - Octanove Vocabulary Profile C1/C2 v1.0 — CC BY-SA 4.0.

Both permit commercial use; both require attribution. That attribution lives in
wordlists/README.md and must also appear in the app's about screen.
"""

import csv
import re
from collections import Counter

from . import config

SOURCES_DIR = config.ROOT / "wordlists" / "sources"
CEFRJ = SOURCES_DIR / "cefrj-vocabulary-profile-1.5.csv"
OCTANOVE = SOURCES_DIR / "octanove-vocabulary-profile-c1c2-1.0.csv"
OUT = config.ROOT / "wordlists" / "targets.tsv"

# Only parts of speech that can carry the meaning of a sentence-completion
# item. A determiner or preposition blank tests grammar, not vocabulary, and
# the exam's completion section is a vocabulary section.
USABLE_POS = {"noun", "verb", "adjective", "adverb"}

# A1 is too easy to be worth generating against — the exam's floor is well
# above it — and C2 sits above the exemption threshold. Keep the range that
# maps onto real AMIRNET score bands.
USABLE_LEVELS = ("A2", "B1", "B2", "C1")

# Single, plain words only. Multi-word headwords, slashed variants
# ("a.m./A.M."), and hyphenated forms don't fit cleanly into a single blank.
WORD_RE = re.compile(r"^[a-z]+$")


def _read(path):
    if not path.exists():
        raise SystemExit(
            f"Missing source file: {path}\n"
            f"Download the datasets first — see wordlists/README.md."
        )
    with open(path, encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def main() -> None:
    rows = _read(CEFRJ) + _read(OCTANOVE)

    # A headword can appear at several levels with different parts of speech.
    # Keep the EASIEST level it appears at: if a learner meets "issue" as a
    # B1 noun, the word is known by B1, and generating it as C1 would overstate
    # the difficulty of the resulting question.
    order = {lvl: i for i, lvl in enumerate(("A1", "A2", "B1", "B2", "C1", "C2"))}
    best: dict[str, tuple[str, str]] = {}

    for row in rows:
        word = (row.get("headword") or "").strip().lower()
        pos = (row.get("pos") or "").strip().lower()
        level = (row.get("CEFR") or "").strip().upper()

        if pos not in USABLE_POS:
            continue
        if level not in USABLE_LEVELS:
            continue
        if not WORD_RE.match(word) or len(word) < 3:
            continue

        current = best.get(word)
        if current is None or order[level] < order[current[1]]:
            best[word] = (pos, level)

    entries = sorted(
        (w, pos, lvl) for w, (pos, lvl) in best.items()
    )

    with open(OUT, "w", encoding="utf-8", newline="") as f:
        f.write("# Generated by `python -m pipeline.build_wordlist` — do not edit by hand.\n")
        f.write("# Sources: CEFR-J Wordlist v1.5 (Tono Lab, TUFS) and\n")
        f.write("# Octanove Vocabulary Profile C1/C2 v1.0 (CC BY-SA 4.0).\n")
        f.write("# Format: word<TAB>pos<TAB>cefr\n")
        for word, pos, level in entries:
            f.write(f"{word}\t{pos}\t{level}\n")

    by_level = Counter(lvl for _, _, lvl in entries)
    by_pos = Counter(pos for _, pos, _ in entries)

    print(f"Wrote {len(entries)} target words to {OUT}")
    print("  by CEFR level:", dict(sorted(by_level.items())))
    print("  by part of speech:", dict(sorted(by_pos.items(), key=lambda x: -x[1])))


if __name__ == "__main__":
    main()
